# Generated by Django 5.1.5 on 2025-02-05 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='자기소개'),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='nickname',
            field=models.CharField(max_length=30, unique=True, verbose_name='닉네임'),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='프로필사진'),
        ),
    ]
