# Generated by Django 5.1.5 on 2025-02-09 20:46

from django.db import migrations

# 지역 카테고리
categories = [
    "대한민국",
    "일본",
    "중국",
    "북미",
    "남미",
    "동아시아",
    "동남아시아",
    "중앙아시아",
    "서남아시아",
    "인도",
    "서유럽",
    "동유럽",
    "북유럽",
    "남유럽",
    "아프리카",
    "중동",
    "오세아니아",
    "기타",
]


def create_initial_categories(apps, schema_editor):
    Category = apps.get_model("blog", "Category")

    for category_name in categories:
        Category.objects.create(name=category_name)


def reverse_categories(apps, schema_editor):
    Category = apps.get_model("yourapp", "Category")
    Category.objects.filter(name__in=categories).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_category_post_category"),
    ]

    operations = [migrations.RunPython(create_initial_categories, reverse_categories)]
