# Generated by Django 5.1.5 on 2025-02-10 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ['-created_at'], 'verbose_name': '연재물', 'verbose_name_plural': '연재물 목록'},
        ),
        migrations.AlterField(
            model_name='post',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.series', verbose_name='연재물'),
        ),
    ]
