# Generated by Django 5.1.5 on 2025-02-10 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
