# Generated by Django 5.1.5 on 2025-02-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_delete_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_subscribers_only',
            field=models.BooleanField(default=False, verbose_name='구독자 전용'),
        ),
    ]
